openai:
  api_base: "https://openrouter.ai/api/v1"
  api_key: "sk-or-v1-9ba97432dcxbd642arefyouftryfthisfapifkeyf1b2b5ax367103qc5e7"
default_generate_stable_diffsution_prompt:
  system : "You are an assistant bot.Follow the instructions and don't interpret the content too much.Be careful to answer in English."
  user: "I want you to act as a prompt generator for AI paintings. Your job is to provide detailed and creative descriptions that will inspire the AI to create unique and interesting images. You can choose one or more of [Lighting, Background, Art Style, Physical Characteristics, Behavior, Demeanor, Look, Period, Effects] to adjust or add details to the description to fit the theme as much as possible. When the scene description is complete, you can output \"Scene Introduction:\" and append your introduction to the tag. Please generate a prompt for this topic:\n{}"
default_translate_prompt: 
  system: "You are an assistant bot."
  user: "I want you to act as an English translator, Your answer is concise without any meaningless text, do not write explanations, now, translate the following sentence:\n \"{}\""
default_chat_prompt: 
  system: "You are an assistant bot."
  user: ""
default_model: "nousresearch/nous-capybara-7b:free"
models:
  - "nousresearch/nous-capybara-7b:free"
  - "mistralai/mistral-7b-instruct:free"
  - "gryphe/mythomist-7b:free"
  - "undi95/toppy-m-7b:free"
  - "openrouter/cinematika-7b:free"
  - "google/gemma-7b-it:free"
  - "neversleep/noromaid-mixtral-8x7b-instruct"
  - "nousresearch/nous-hermes-llama2-13b"
  - "nousresearch/nous-hermes-2-mixtral-8x7b-dpo"
  - "nousresearch/nous-hermes-2-mixtral-8x7b-sft"
  - "gryphe/mythomax-l2-13b"
  - "nousresearch/nous-capybara-7b"
  - "teknium/openhermes-2-mistral-7b"
  - "open-orca/mistral-7b-openorca"
  - "huggingfaceh4/zephyr-7b-beta"
  - "openai/gpt-3.5-turbo-0125"
  - "google/gemini-pro"
  - "perplexity/sonar-small-chat"
  - "perplexity/sonar-medium-chat"
  - "cognitivecomputations/dolphin-mixtral-8x7b"
  - "anthropic/claude-instant-1.2"



